### PR TITLE
Added section Translators

### PR DESCRIPTION
**Pull request by tiborepcek**
I think, it would by nice to appreciate the work publicly. ;)

### CODE REVIEW

**Comment by marchellodev** [comment]
Yeah, sure, sorry about that :)
In Sharik v3 there will be a whole page with all contributors

Could you please add other translators too? You can check other pull requests.
Thanks

**Comment by tiborepcek** [comment]
In PR i found:

- Polish by [Atrate](https://github.com/Atrate)
- Arabic by [Yazeed AlKhalaf](https://github.com/YazeedAlKhalaf)
- Brazilian Portuguese by [mezysinc](https://github.com/mezysinc)

Is it all?

**Comment by marchellodev** [comment]
Also Gujarati and Hindi by [mrfoxie](https://github.com/mrfoxie)

**Comment by tiborepcek** [comment]
PR #21 closes this PR.

**Pull request closed without merging**
