### PR TITLE
Update in_hi.dart to native hindi

### PR DESCRIPTION
**Pull request by darpan5552**
Translation currently available is more like directly translated from one language to another. However, language doesn't work that way rather its a method to approach people. I tried to convert hindi translation to native language that i think would be more readable.

I compared the use of each line in app. Arrangement of Subject, Verb and predicate is different in different languages. So, I adjusted some text to better match the flow of language.

### CODE REVIEW

**Comment by marchellodev** [comment]
@mrfoxie What do you think ? :)

**Comment by darpan5552** [comment]
There are some files in `/fastlane/metadata/android/hi`, may be for play store description.
Style of language used there is quite satisfactory to me. Still I wanted to edit some words.

**Comment by mrfoxie** [comment]
@marchellodev no problem for my side 
@darpan5552 I asked many of my friends and other people regarding translations and I took there help and then I wrote it down and if you think that it's improper or incorrect then you can change it there ☺☺

**Comment by marchellodev** [comment]
If I only knew hindi :)

All right, I'm going to accept the changes. Thanks @darpan5552 @mrfoxie

**Comment by darpan5552** [comment]
@marchellodev Please, send me the apk file before making new release. I wanted to verify it again from my side.

**Pull request merged**
