### PR TITLE
➕ Add Arabic Support

### PR DESCRIPTION
**Pull request by YazeedAlKhalaf**
In this PR I added Arabic language support 🚀🙈

### CODE REVIEW

**Comment by marchellodev** [comment]
Could you change the fonts `Andika` and `Comfortaa` to similar that support Arabic?
Please change them in the [translation file](https://github.com/marchellodev/sharik/pull/14/commits/71c40b7976a9bd20257d2c54f4a6e4b37e572d6b#diff-45e6707b1159e7230c0acad2e522c23a83266f6585177a34612be868420866b8R49) and download proper versions to the [google_fonts ](https://github.com/marchellodev/sharik/tree/master/google_fonts) folder.

For the fonts, refer to https://fonts.google.com/?subset=arabic
Also, make sure that fonts' license permits use in open-source projects.


Thank you!

**Comment by YazeedAlKhalaf** [comment]
> Could you change the fonts `Andika` and `Comfortaa` to similar that support Arabic?
> Please change them in the [translation file](https://github.com/marchellodev/sharik/pull/14/commits/71c40b7976a9bd20257d2c54f4a6e4b37e572d6b#diff-45e6707b1159e7230c0acad2e522c23a83266f6585177a34612be868420866b8R49) and download proper versions to the [google_fonts ](https://github.com/marchellodev/sharik/tree/master/google_fonts) folder.
> 
> For the fonts, refer to https://fonts.google.com/?subset=arabic
> Also, make sure that fonts' license permits use in open-source projects.
> 
> Thank you!

Sure!
Tajawal: https://fonts.google.com/specimen/Tajawal?subset=arabic
Changa: https://fonts.google.com/specimen/Changa?subset=arabic

**Comment by YazeedAlKhalaf** [comment]
There is a license file for each font from Google Fonts, Do I add them?

**Comment by marchellodev** [comment]
No, I'll add them later myself. I'm going to create a dialog for that

**Comment by YazeedAlKhalaf** [comment]
Great! 🚀

**Comment by marchellodev** [comment]
Could you please remove ExtraBold, Medium, etc? They are not used and will only take space.
Only regular and bold are used

**Comment by YazeedAlKhalaf** [comment]
> Could you please remove ExtraBold, Medium, etc? They are not used and will only take space.
> Only regular and bold are used

Done 🚀

**Comment by marchellodev** [comment]
Cool, everything else seems fine. Thanks!

**Comment by YazeedAlKhalaf** [comment]
> Cool, everything else seems fine. Thanks!

You're very welcome!

**Comment by marchellodev** [comment]
However, I'm not going to publish the new version right away. I want to improve the architecture of the app a bit and add some new features (see v3 branch).
I hope this won't take too long

**Comment by YazeedAlKhalaf** [comment]
Cool 😎

**Pull request merged**
